# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Texlate < Formula
  desc ""
  homepage ""
  version "0.1.3"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/SirRippovMaple/texlate/releases/download/v0.1.3/texlate_0.1.3_Darwin_x86_64.tar.gz"
    sha256 "cb4cd10b1829589d04cd6815b3d11241758763e8212fbb5c838c645d05b87596"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/SirRippovMaple/texlate/releases/download/v0.1.3/texlate_0.1.3_Darwin_arm64.tar.gz"
    sha256 "e85b72d460def69abe6696a84a613259c7c86e6c8b86a5648cdb5251db33aefd"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/SirRippovMaple/texlate/releases/download/v0.1.3/texlate_0.1.3_Linux_x86_64.tar.gz"
    sha256 "e272e7e08c2488708c89ef0f47fb229540683b16c63a0c67fa86a8bcc5a1f15b"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/SirRippovMaple/texlate/releases/download/v0.1.3/texlate_0.1.3_Linux_arm64.tar.gz"
    sha256 "eed15c598253ca1bce2ccdb5ef74d123100d639ba35758ccbe402567645742a4"
  end

  def install
    bin.install "texlate"
  end
end
